[package]
name = "vaulty"
version = "1.0.1"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
rpassword = "7.2"
rand_core = "0.6"
base64 = "0.20"
scrypt = "0.10"
chacha20poly1305 = "0.10"
